### PR TITLE
Моя версия, которая залита на сервер

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#97` is in scope.

**Comment by DronMDF** [comment]
@0crat out

**Comment by DronMDF** [comment]
@0crat out

**Comment by DronMDF** [comment]
@0crat out

**Comment by yegor256** [comment]
@DronMDF works for me: https://github.com/zerocracy/datum/issues/158 Can you please try again, maybe it was a temporary down time.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#97` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @dronmdf, total is [+1475](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @michaelo0, total is [+480](http://www.0crat.com/u/michaelo0).

**Pull request merged**
