### PR TITLE
INSTALL.md

### PR DESCRIPTION
**Pull request by BarbaraGrape**

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#32` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#32` assigned to @chniks, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/32#issuecomment-341881145))

@DronMDF @chniks resigned from `gh:dronmdf/telebot#32`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/32#issuecomment-341881145))

@DronMDF Job `gh:dronmdf/telebot#32` is now out of scope.

**Pull request merged**
