### PR TITLE
Инструкция для входа в проект

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#14` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+210](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#14` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/14#issuecomment-333323851))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#14`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#14` assigned to @olejka, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/14#issuecomment-333325913))

@DronMDF Job `gh:dronmdf/telebot#14` is now out of scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+255](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
+30 points just awarded to @olejka, total is [+30](http://www.0crat.com/u/olejka).

**Pull request merged**
