### PR TITLE
commit #38

### PR DESCRIPTION
**Pull request by yuran8shon**
новый код

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#53` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#53` assigned to @barbaragrape, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/53#issuecomment-343907365))

@DronMDF @barbaragrape resigned from `gh:dronmdf/telebot#53`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/53#issuecomment-343907365))

@DronMDF Job `gh:dronmdf/telebot#53` is now out of scope.

**Pull request merged**
