### PR TITLE
new name of file. Server part. #6

### PR DESCRIPTION
**Pull request by sminux**

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#31` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @sminux, total is [+30](http://www.0crat.com/u/sminux).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#31` assigned to @yuran8shon, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Review by yuran8shon — APPROVED** [review]
nice work- well done

**Review by DronMDF — APPROVED** [review]
ok

**Comment by 0crat** [comment]
@yuran8shon this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@yuran8shon resigned from `gh:dronmdf/telebot#31`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#31` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#31` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#31` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/31#issuecomment-346138994))

@DronMDF @meladark resigned from `gh:dronmdf/telebot#31`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/31#issuecomment-346138994))

@DronMDF Job `gh:dronmdf/telebot#31` is now out of scope.

**Pull request merged**
