### PR TITLE
Create error-output

### PR DESCRIPTION
**Pull request by olejka**
#16

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#27` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @olejka, total is [+45](http://www.0crat.com/u/olejka).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#27` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Review by DronMDF — APPROVED** [review]
Ладно, не возражаю. :)

**Review by olejka — COMMENTED** [review]
:)

**Comment by olejka** [comment]
Если я правильно понял, то я сделал Submitted

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 4587b03 2017-10-07T20:26:14
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Can't post anything to dronmdf/telebot#27, too many comments already
	at sun.reflect.GeneratedConstructorAccessor638.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at com.zerocracy.stk.pm.comm.notify_in_github.safe(notify_in_github.groovy:92)
	at com.zerocracy.stk.pm.comm.notify_in_github$safe.callStatic(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_in_github.exec(notify_in_github.groovy:65)
	at sun.reflect.GeneratedMethodAccessor504.invoke(Unknown Source)
	at sun.reflect.Delega...
```

**Comment by DronMDF** [comment]
@olejka ПО поводу Submit - я ошибся, эта штука называется Approve...

image

0crat назначил тебя ответственным за  #28 

Но проблема в том, что там уже возник конфликт. Два разработчика написали main.py, и это надо разруливать теперь. Это должен делать @sminux.

**Comment by olejka** [comment]
У меня нет кнопки  Approve , хотя она есть в пул реквесте "server"

**Comment by 0crat** [comment]
@dronmdf this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@dronmdf resigned from `gh:dronmdf/telebot#27`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#27` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#27` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#27` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#27` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#27` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#27` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/27#issuecomment-346138797))

@DronMDF @meladark resigned from `gh:dronmdf/telebot#27`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/27#issuecomment-346138797))

@DronMDF Job `gh:dronmdf/telebot#27` is now out of scope.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/27#issuecomment-346138797))

@DronMDF Oops! Job `gh:dronmdf/telebot#27` is not in scope.

**Pull request merged**
