### PR TITLE
#68: Формирование реации на входящие сообщения

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#72` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#72` assigned to @yuran8shon, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/72#issuecomment-346137806))

@DronMDF @yuran8shon resigned from `gh:dronmdf/telebot#72`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/72#issuecomment-346137806))

@DronMDF Job `gh:dronmdf/telebot#72` is now out of scope.

**Pull request merged**
