### PR TITLE
Merge pull request 20/11/17

### PR DESCRIPTION
**Pull request by sminux**

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#71` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#71` assigned to @michaelo0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@sminux Что-то как-то много всего...
Судя по тому, что files changed: 0
Вероятно я все эти изменения уже влил.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/71#issuecomment-346138042))

@DronMDF @michaelo0 resigned from `gh:dronmdf/telebot#71`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/71#issuecomment-346138042))

@DronMDF Job `gh:dronmdf/telebot#71` is now out of scope.

**Pull request closed without merging**
