### PR TITLE
#63 Реализация БД через tinydb

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#64` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#64` assigned to @olejka, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/64#issuecomment-341880936))

@DronMDF @olejka resigned from `gh:dronmdf/telebot#64`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/64#issuecomment-341880936))

@DronMDF Job `gh:dronmdf/telebot#64` is now out of scope.

**Pull request merged**
