### PR TITLE
added server use cause description

### PR DESCRIPTION
**Pull request by ChNikS**
Список команд бота #13

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#26` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @chniks, total is [+15](http://www.0crat.com/u/chniks).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#26` assigned to @alexandersamrega, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@ChNikS Ты первый. Поздравляю.

**Comment by DronMDF** [comment]
@0crat assign me

**Review by DronMDF — APPROVED** [review]

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/26#issuecomment-335710504))

@DronMDF Job `gh:dronmdf/telebot#26` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+435](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
@dronmdf this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@dronmdf resigned from `gh:dronmdf/telebot#26`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#26` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#26` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/26#issuecomment-346138718))

@DronMDF @meladark resigned from `gh:dronmdf/telebot#26`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/26#issuecomment-346138718))

@DronMDF Job `gh:dronmdf/telebot#26` is now out of scope.

**Pull request merged**
