### PR TITLE
#49 StDispatch

### PR DESCRIPTION
**Pull request by sminux**

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#61` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#61` assigned to @chniks, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@sminux Последний коммит прилип к этому пулл реквесту...
Вообще по хорошему так нельзя.

И что касается БД - для того, чтобы закрыть #39 нет необходимости писать tunyDB имплементацию. Реализация хранилища не зависит от реализации БД. Как и должно быть. И реализовывать ее могут разные люди в разных запросах.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/61#issuecomment-340551086))

@DronMDF Job `gh:dronmdf/telebot#61` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+685](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by DronMDF** [comment]
Разделил этот запрос на два. #64 и #65 
Этот пусть пока висит.

**Comment by DronMDF** [comment]
Закрываем, толку от него нет.

**Comment by 0crat** [comment]
@dronmdf this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@dronmdf resigned from `gh:dronmdf/telebot#61`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#61` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#61` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#61` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#61` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#61` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#61` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/61#issuecomment-346138635))

@DronMDF @dronmdf resigned from `gh:dronmdf/telebot#61`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/61#issuecomment-346138635))

@DronMDF Job `gh:dronmdf/telebot#61` is now out of scope.

**Pull request closed without merging**
