### PR TITLE
req

### PR DESCRIPTION
**Pull request by meladark**
new

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#33` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#33` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Этот пулреквест по запросу #22

**Review by sminux — COMMENTED** [review]
good job

**Comment by DronMDF** [comment]
@sminux Уже замержено. Я не стал ждать, пока все сделают ревью.
Но хотел заметить, когда делаешь ревью - слова не играют роли. :)
Главное - поставить Submitted в разделе "Files changed". (Там справа большая зеленая кнопка).
Ну это на будущее.

**Comment by 0crat** [comment]
@sminux this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@sminux resigned from `gh:dronmdf/telebot#33`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#33` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#33` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#33` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#33` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#33` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#33` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/33#issuecomment-346139036))

@DronMDF @yuran8shon resigned from `gh:dronmdf/telebot#33`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/33#issuecomment-346139036))

@DronMDF Job `gh:dronmdf/telebot#33` is now out of scope.

**Pull request merged**
