### PR TITLE
#56

### PR DESCRIPTION
**Pull request by sminux**

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#73` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#73` assigned to @michaelo0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/73#issuecomment-346137926))

@DronMDF @michaelo0 resigned from `gh:dronmdf/telebot#73`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/73#issuecomment-346137926))

@DronMDF Job `gh:dronmdf/telebot#73` is now out of scope.

**Pull request merged**
