### PR TITLE
#61: Дополнительная зависимость от tinydb

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#62` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#62` assigned to @chniks, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/62#issuecomment-341881168))

@DronMDF @chniks resigned from `gh:dronmdf/telebot#62`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/62#issuecomment-341881168))

@DronMDF Job `gh:dronmdf/telebot#62` is now out of scope.

**Pull request closed without merging**
