### PR TITLE
Test

### PR DESCRIPTION
**Pull request by 1640max**
new

### CODE REVIEW

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#34` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#34` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Этот реквест по запросу #21

**Review by sminux — COMMENTED** [review]
hurry up, man

**Comment by 0crat** [comment]
@sminux this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@sminux resigned from `gh:dronmdf/telebot#34`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#34` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#34` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#34` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#34` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#34` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#34` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/34#issuecomment-346139092))

@DronMDF @meladark resigned from `gh:dronmdf/telebot#34`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/34#issuecomment-346139092))

@DronMDF Job `gh:dronmdf/telebot#34` is now out of scope.

**Pull request merged**
