### PR TITLE
#58: Перехват исключений

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#69` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#69` assigned to @1640max, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/69#issuecomment-346135826))

@DronMDF @1640max resigned from `gh:dronmdf/telebot#69`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/69#issuecomment-346135826))

@DronMDF Job `gh:dronmdf/telebot#69` is now out of scope.

**Pull request merged**
