### PR TITLE
Update Zerocracy badge location

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#25` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+405](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#25` assigned to @pavelonex, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Review by PavelOnex — COMMENTED** [review]
Nice one

**Comment by DronMDF** [comment]
@PavelOnex Для подтверждения в Review нужно ставить статус Approved.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/25#issuecomment-341880658))

@DronMDF @pavelonex resigned from `gh:dronmdf/telebot#25`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/25#issuecomment-341880658))

@DronMDF Job `gh:dronmdf/telebot#25` is now out of scope.

**Pull request merged**
